/*CREATE TABLE ABONENTS(
  MSISDM_ID NUMBER NOT NULL,
  ABONENT_NAME VARCHAR(50) NOT NULL,
  CONSTRAINT MSISDM_PK PRIMARY KEY(MSISDM_ID)  
);*/

/*CREATE TABLE CARDS(
  PAN_ID NUMBER NOT NULL,
  EXPIRE DATE NOT NULL,
  MSISDM_ID NUMBER NOT NULL,
  CONSTRAINT CARD_PK PRIMARY KEY(PAN_ID),
  CONSTRAINT CARD_FK FOREIGN KEY(MSISDM_ID) REFERENCES ABONENTS(MSISDM_ID)
);*/

/*CREATE OR REPLACE FUNCTION NumberCards 
(CARD_IN NUMBER) 
RETURN NUMBER 
IS
NUM_CARD NUMBER;
BEGIN 
SELECT COUNT(PAN_ID)
INTO NUM_CARD
FROM CARDS
WHERE MSISDM_ID = CARD_IN;
RETURN NUM_CARD; 
END NumberCards;*/

/*SELECT NumberCards(MSISDM_ID) FROM ABONENTS
WHERE MSISDM_ID = 11111;*/
